name = "biluplus"
main = "src/index-v2.ts"
account_id = "f8622bda39b193df337532b54aff523b"
compatibility_date = "2024-03-07"
compatibility_flags = ["nodejs_compat"]

[observability]
enabled = true
head_sampling_rate = 1

[[kv_namespaces]]
binding = "KV"
id = "2de8a93c7dba459299b6317edea53dbc"

[[d1_databases]]
binding = "DB"
database_name = "bilu"
database_id = "2df96960-e625-494b-a94b-18e6e032c3cb"
migrations_dir = "migrations"

[[analytics_engine_datasets]]
binding = "ANALYTICS"
dataset = "bilu_analytics"

[vars]
JWT_SECRET = "K7gNU3sdo+OL0wNhqoVWhr3g6s1xYv72ol/pe/Unols="
ADMIN_EMAIL = "admin@yourdomain.com"